name: bip39
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: andh <email@example.com>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  resource: ^2.1.4
  pointycastle: ^1.0.0-rc2
  hex: ^0.1.2
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
